import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type LanguageCode = "en" | "it" | "es" | "de" | "fr" | "pt";

type TranslationDict = Record<string, string>;

interface LanguageContextValue {
  language: LanguageCode;
  locale: string;
  setLanguage: (language: LanguageCode) => void;
  t: (key: string, params?: Record<string, string | number>, fallback?: string) => string;
}

const STORAGE_KEY = "cx_portal_language";

export const LANGUAGE_META: Array<{
  code: LanguageCode;
  label: string;
  flag: string;
}> = [
  { code: "en", label: "English", flag: "🇺🇸" },
  { code: "it", label: "Italiano", flag: "🇮🇹" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "pt", label: "Português", flag: "🇵🇹" },
];

const LANGUAGE_LOCALES: Record<LanguageCode, string> = {
  en: "en-US",
  it: "it-IT",
  es: "es-ES",
  de: "de-DE",
  fr: "fr-FR",
  pt: "pt-PT",
};

const DICTIONARY: Record<LanguageCode, TranslationDict> = {
  en: {
    "header.active": "Active",
    "header.inactive": "Inactive",
    "header.adminAccount": "Admin Account",
    "header.wallet": "Wallet",
    "header.dtmfNotifications": "DTMF Notifications",
    "header.noDtmfNotifications": "No DTMF notifications yet.",
    "header.clear": "Clear",
    "header.openProfile": "Open profile",
    "header.openAdminSecurity": "Open admin security",
    "header.notSet": "Not Set",
    "header.now": "Now",
    "header.dtmfFrom": "DTMF '{{dtmf}}' from {{number}}",
    "header.language": "Language",

    "menu.dashboard": "Dashboard",
    "menu.campaigns": "Campaigns",
    "menu.campaign": "Campaign",
    "menu.runCampaign": "Run Campaign",
    "menu.campaignHistory": "Campaign History",
    "menu.contacts": "Contacts",
    "menu.liveCalls": "Live Calls",
    "menu.callLogs": "Call Logs (CDRs)",
    "menu.callerId": "Caller ID",
    "menu.subscription": "Subscription",
    "menu.settings": "Settings",
    "menu.logout": "Logout",

    "menu.adminDashboard": "Admin Dashboard",
    "menu.telegramUsers": "Telegram Users",
    "menu.adminLiveLogs": "Live Calls & Logs",
    "menu.userCampaigns": "User Campaigns",
    "menu.allUsersCdrs": "All Users CDRs",
    "menu.activityLogs": "Activity Logs",
    "menu.broadcast": "Broadcast",
    "menu.adminSecurity": "Admin Security",

    "login.title": "Sign in to your account",
    "login.subtitle": "Login with SIP credentials of CyberX Account",
    "login.username": "Username",
    "login.password": "Password",
    "login.rememberMe": "Remember me",
    "login.forgotPassword": "Forgot password?",
    "login.signIn": "Sign In",
    "login.signingIn": "Signing in...",
    "login.usernamePlaceholder": "Username",
    "login.passwordPlaceholder": "Password",
    "login.hidePassword": "Hide password",
    "login.showPassword": "Show password",

    "page.dashboard.title": "Dashboard",
    "page.dashboard.subtitle": "Welcome back! Here's your overview.",
    "page.campaigns.title": "Campaigns",
    "page.campaigns.subtitle": "Manage your autodialer campaigns",
    "page.runCampaign.title": "Run Campaign",
    "page.runCampaign.subtitle": "Launch by campaign + selected contact list, then monitor live calls, logs, and DTMF results.",
    "page.campaignHistory.title": "Campaign History",
    "page.campaignHistory.subtitle": "Complete run history with answered, failed, DTMF hits, and audio/TTS details.",
    "page.contacts.title": "Contacts",
    "page.contacts.subtitle": "Create and manage multiple contact lists.",
    "page.liveCalls.title": "Live Calls",
    "page.liveCalls.subtitle": "Real-time call monitoring",
    "page.cdr.title": "Call Logs (CDRs)",
    "page.cdr.subtitle": "Campaign call records from local dialer DB.",
    "page.callerId.title": "SIP Accounts",
    "page.callerId.subtitle": "Manage SIP users, trunk accounts, and caller IDs.",
    "page.settings.title": "Settings",
    "page.settings.subtitle": "Choose your default SIP account and caller ID for campaigns.",
    "page.profile.title": "Profile",
    "page.profile.subtitle": "Account identity, security details, and subscription summary.",
    "page.subscription.title": "Subscription",
    "page.subscription.subtitle": "Activate autodialer plans from your CyberX Account balance.",
  },
  it: {
    "header.active": "Attivo",
    "header.inactive": "Inattivo",
    "header.adminAccount": "Account Admin",
    "header.wallet": "Portafoglio",
    "header.dtmfNotifications": "Notifiche DTMF",
    "header.noDtmfNotifications": "Nessuna notifica DTMF.",
    "header.clear": "Cancella",
    "header.openProfile": "Apri profilo",
    "header.openAdminSecurity": "Apri sicurezza admin",
    "header.notSet": "Non impostato",
    "header.now": "Ora",
    "header.dtmfFrom": "DTMF '{{dtmf}}' da {{number}}",
    "header.language": "Lingua",

    "menu.dashboard": "Dashboard",
    "menu.campaigns": "Campagne",
    "menu.campaign": "Campagna",
    "menu.runCampaign": "Avvia Campagna",
    "menu.campaignHistory": "Storico Campagne",
    "menu.contacts": "Contatti",
    "menu.liveCalls": "Chiamate Live",
    "menu.callLogs": "Log Chiamate (CDR)",
    "menu.callerId": "Caller ID",
    "menu.subscription": "Abbonamento",
    "menu.settings": "Impostazioni",
    "menu.logout": "Esci",

    "menu.adminDashboard": "Dashboard Admin",
    "menu.telegramUsers": "Utenti Telegram",
    "menu.adminLiveLogs": "Chiamate Live e Log",
    "menu.userCampaigns": "Campagne Utenti",
    "menu.allUsersCdrs": "CDR Tutti gli Utenti",
    "menu.activityLogs": "Log Attività",
    "menu.broadcast": "Broadcast",
    "menu.adminSecurity": "Sicurezza Admin",

    "login.title": "Accedi al tuo account",
    "login.subtitle": "Accedi con credenziali SIP del tuo account CyberX",
    "login.username": "Username",
    "login.password": "Password",
    "login.rememberMe": "Ricordami",
    "login.forgotPassword": "Password dimenticata?",
    "login.signIn": "Accedi",
    "login.signingIn": "Accesso in corso...",
    "login.usernamePlaceholder": "Username",
    "login.passwordPlaceholder": "Password",
    "login.hidePassword": "Nascondi password",
    "login.showPassword": "Mostra password",

    "page.dashboard.title": "Dashboard",
    "page.dashboard.subtitle": "Bentornato! Ecco una panoramica.",
    "page.campaigns.title": "Campagne",
    "page.campaigns.subtitle": "Gestisci le tue campagne autodialer",
    "page.runCampaign.title": "Avvia Campagna",
    "page.runCampaign.subtitle": "Avvia con campagna + lista contatti, poi monitora chiamate live, log e risultati DTMF.",
    "page.campaignHistory.title": "Storico Campagne",
    "page.campaignHistory.subtitle": "Storico completo con risposte, fallimenti, DTMF e dettagli audio/TTS.",
    "page.contacts.title": "Contatti",
    "page.contacts.subtitle": "Crea e gestisci più liste contatti.",
    "page.liveCalls.title": "Chiamate Live",
    "page.liveCalls.subtitle": "Monitoraggio chiamate in tempo reale",
    "page.cdr.title": "Log Chiamate (CDR)",
    "page.cdr.subtitle": "Record chiamate campagna dal DB dialer locale.",
    "page.callerId.title": "Account SIP",
    "page.callerId.subtitle": "Gestisci utenti SIP, trunk account e caller ID.",
    "page.settings.title": "Impostazioni",
    "page.settings.subtitle": "Scegli account SIP e caller ID predefiniti per le campagne.",
    "page.profile.title": "Profilo",
    "page.profile.subtitle": "Identità account, sicurezza e riepilogo abbonamento.",
    "page.subscription.title": "Abbonamento",
    "page.subscription.subtitle": "Attiva piani autodialer dal saldo del tuo account CyberX.",
  },
  es: {
    "header.active": "Activo",
    "header.inactive": "Inactivo",
    "header.adminAccount": "Cuenta Admin",
    "header.wallet": "Billetera",
    "header.dtmfNotifications": "Notificaciones DTMF",
    "header.noDtmfNotifications": "Aún no hay notificaciones DTMF.",
    "header.clear": "Limpiar",
    "header.openProfile": "Abrir perfil",
    "header.openAdminSecurity": "Abrir seguridad admin",
    "header.notSet": "No configurado",
    "header.now": "Ahora",
    "header.dtmfFrom": "DTMF '{{dtmf}}' de {{number}}",
    "header.language": "Idioma",

    "menu.dashboard": "Panel",
    "menu.campaigns": "Campañas",
    "menu.campaign": "Campaña",
    "menu.runCampaign": "Ejecutar Campaña",
    "menu.campaignHistory": "Historial de Campañas",
    "menu.contacts": "Contactos",
    "menu.liveCalls": "Llamadas en Vivo",
    "menu.callLogs": "Registros de Llamadas (CDR)",
    "menu.callerId": "Caller ID",
    "menu.subscription": "Suscripción",
    "menu.settings": "Configuración",
    "menu.logout": "Cerrar sesión",

    "menu.adminDashboard": "Panel Admin",
    "menu.telegramUsers": "Usuarios Telegram",
    "menu.adminLiveLogs": "Llamadas y Logs en Vivo",
    "menu.userCampaigns": "Campañas de Usuarios",
    "menu.allUsersCdrs": "CDR de Todos los Usuarios",
    "menu.activityLogs": "Logs de Actividad",
    "menu.broadcast": "Difusión",
    "menu.adminSecurity": "Seguridad Admin",

    "login.title": "Inicia sesión en tu cuenta",
    "login.subtitle": "Inicia sesión con credenciales SIP de tu cuenta CyberX",
    "login.username": "Usuario",
    "login.password": "Contraseña",
    "login.rememberMe": "Recordarme",
    "login.forgotPassword": "¿Olvidaste la contraseña?",
    "login.signIn": "Iniciar sesión",
    "login.signingIn": "Iniciando sesión...",
    "login.usernamePlaceholder": "Usuario",
    "login.passwordPlaceholder": "Contraseña",
    "login.hidePassword": "Ocultar contraseña",
    "login.showPassword": "Mostrar contraseña",

    "page.dashboard.title": "Panel",
    "page.dashboard.subtitle": "¡Bienvenido de nuevo! Aquí tienes tu resumen.",
    "page.campaigns.title": "Campañas",
    "page.campaigns.subtitle": "Gestiona tus campañas de autodialer",
    "page.runCampaign.title": "Ejecutar Campaña",
    "page.runCampaign.subtitle": "Lanza por campaña + lista de contactos seleccionada y monitorea llamadas, logs y DTMF.",
    "page.campaignHistory.title": "Historial de Campañas",
    "page.campaignHistory.subtitle": "Historial completo con respondidas, fallidas, DTMF y detalles de audio/TTS.",
    "page.contacts.title": "Contactos",
    "page.contacts.subtitle": "Crea y gestiona múltiples listas de contactos.",
    "page.liveCalls.title": "Llamadas en Vivo",
    "page.liveCalls.subtitle": "Monitoreo de llamadas en tiempo real",
    "page.cdr.title": "Registros de Llamadas (CDR)",
    "page.cdr.subtitle": "Registros de campaña desde la base local del dialer.",
    "page.callerId.title": "Cuentas SIP",
    "page.callerId.subtitle": "Gestiona usuarios SIP, cuentas trunk y caller IDs.",
    "page.settings.title": "Configuración",
    "page.settings.subtitle": "Elige cuenta SIP y caller ID por defecto para campañas.",
    "page.profile.title": "Perfil",
    "page.profile.subtitle": "Identidad de cuenta, seguridad y resumen de suscripción.",
    "page.subscription.title": "Suscripción",
    "page.subscription.subtitle": "Activa planes autodialer con el saldo de tu cuenta CyberX.",
  },
  de: {
    "header.active": "Aktiv",
    "header.inactive": "Inaktiv",
    "header.adminAccount": "Admin-Konto",
    "header.wallet": "Wallet",
    "header.dtmfNotifications": "DTMF-Benachrichtigungen",
    "header.noDtmfNotifications": "Noch keine DTMF-Benachrichtigungen.",
    "header.clear": "Löschen",
    "header.openProfile": "Profil öffnen",
    "header.openAdminSecurity": "Admin-Sicherheit öffnen",
    "header.notSet": "Nicht gesetzt",
    "header.now": "Jetzt",
    "header.dtmfFrom": "DTMF '{{dtmf}}' von {{number}}",
    "header.language": "Sprache",

    "menu.dashboard": "Dashboard",
    "menu.campaigns": "Kampagnen",
    "menu.campaign": "Kampagne",
    "menu.runCampaign": "Kampagne starten",
    "menu.campaignHistory": "Kampagnenverlauf",
    "menu.contacts": "Kontakte",
    "menu.liveCalls": "Live-Anrufe",
    "menu.callLogs": "Anrufprotokolle (CDR)",
    "menu.callerId": "Caller ID",
    "menu.subscription": "Abonnement",
    "menu.settings": "Einstellungen",
    "menu.logout": "Abmelden",

    "menu.adminDashboard": "Admin-Dashboard",
    "menu.telegramUsers": "Telegram-Nutzer",
    "menu.adminLiveLogs": "Live-Anrufe & Logs",
    "menu.userCampaigns": "Nutzerkampagnen",
    "menu.allUsersCdrs": "CDRs aller Nutzer",
    "menu.activityLogs": "Aktivitätsprotokolle",
    "menu.broadcast": "Broadcast",
    "menu.adminSecurity": "Admin-Sicherheit",

    "login.title": "Bei deinem Konto anmelden",
    "login.subtitle": "Melde dich mit den SIP-Zugangsdaten deines CyberX-Kontos an",
    "login.username": "Benutzername",
    "login.password": "Passwort",
    "login.rememberMe": "Angemeldet bleiben",
    "login.forgotPassword": "Passwort vergessen?",
    "login.signIn": "Anmelden",
    "login.signingIn": "Anmeldung läuft...",
    "login.usernamePlaceholder": "Benutzername",
    "login.passwordPlaceholder": "Passwort",
    "login.hidePassword": "Passwort ausblenden",
    "login.showPassword": "Passwort anzeigen",

    "page.dashboard.title": "Dashboard",
    "page.dashboard.subtitle": "Willkommen zurück! Hier ist dein Überblick.",
    "page.campaigns.title": "Kampagnen",
    "page.campaigns.subtitle": "Verwalte deine Autodialer-Kampagnen",
    "page.runCampaign.title": "Kampagne starten",
    "page.runCampaign.subtitle": "Starte mit Kampagne + Kontaktliste und überwache Live-Anrufe, Logs und DTMF.",
    "page.campaignHistory.title": "Kampagnenverlauf",
    "page.campaignHistory.subtitle": "Kompletter Verlauf mit beantwortet, fehlgeschlagen, DTMF und Audio/TTS-Details.",
    "page.contacts.title": "Kontakte",
    "page.contacts.subtitle": "Erstelle und verwalte mehrere Kontaktlisten.",
    "page.liveCalls.title": "Live-Anrufe",
    "page.liveCalls.subtitle": "Echtzeit-Anrufüberwachung",
    "page.cdr.title": "Anrufprotokolle (CDR)",
    "page.cdr.subtitle": "Kampagnenanrufe aus der lokalen Dialer-Datenbank.",
    "page.callerId.title": "SIP-Konten",
    "page.callerId.subtitle": "Verwalte SIP-Nutzer, Trunk-Konten und Caller IDs.",
    "page.settings.title": "Einstellungen",
    "page.settings.subtitle": "Wähle Standard-SIP-Konto und Caller ID für Kampagnen.",
    "page.profile.title": "Profil",
    "page.profile.subtitle": "Kontoinformationen, Sicherheit und Abo-Zusammenfassung.",
    "page.subscription.title": "Abonnement",
    "page.subscription.subtitle": "Aktiviere Autodialer-Pläne mit deinem CyberX-Kontoguthaben.",
  },
  fr: {
    "header.active": "Actif",
    "header.inactive": "Inactif",
    "header.adminAccount": "Compte Admin",
    "header.wallet": "Portefeuille",
    "header.dtmfNotifications": "Notifications DTMF",
    "header.noDtmfNotifications": "Aucune notification DTMF pour le moment.",
    "header.clear": "Effacer",
    "header.openProfile": "Ouvrir le profil",
    "header.openAdminSecurity": "Ouvrir la sécurité admin",
    "header.notSet": "Non défini",
    "header.now": "Maintenant",
    "header.dtmfFrom": "DTMF '{{dtmf}}' de {{number}}",
    "header.language": "Langue",

    "menu.dashboard": "Tableau de bord",
    "menu.campaigns": "Campagnes",
    "menu.campaign": "Campagne",
    "menu.runCampaign": "Lancer la campagne",
    "menu.campaignHistory": "Historique des campagnes",
    "menu.contacts": "Contacts",
    "menu.liveCalls": "Appels en direct",
    "menu.callLogs": "Journaux d'appels (CDR)",
    "menu.callerId": "Caller ID",
    "menu.subscription": "Abonnement",
    "menu.settings": "Paramètres",
    "menu.logout": "Déconnexion",

    "menu.adminDashboard": "Tableau Admin",
    "menu.telegramUsers": "Utilisateurs Telegram",
    "menu.adminLiveLogs": "Appels & Logs en direct",
    "menu.userCampaigns": "Campagnes utilisateurs",
    "menu.allUsersCdrs": "CDR de tous les utilisateurs",
    "menu.activityLogs": "Journaux d'activité",
    "menu.broadcast": "Diffusion",
    "menu.adminSecurity": "Sécurité Admin",

    "login.title": "Connectez-vous à votre compte",
    "login.subtitle": "Connectez-vous avec les identifiants SIP de votre compte CyberX",
    "login.username": "Nom d'utilisateur",
    "login.password": "Mot de passe",
    "login.rememberMe": "Se souvenir de moi",
    "login.forgotPassword": "Mot de passe oublié ?",
    "login.signIn": "Se connecter",
    "login.signingIn": "Connexion...",
    "login.usernamePlaceholder": "Nom d'utilisateur",
    "login.passwordPlaceholder": "Mot de passe",
    "login.hidePassword": "Masquer le mot de passe",
    "login.showPassword": "Afficher le mot de passe",

    "page.dashboard.title": "Tableau de bord",
    "page.dashboard.subtitle": "Bon retour ! Voici votre aperçu.",
    "page.campaigns.title": "Campagnes",
    "page.campaigns.subtitle": "Gérez vos campagnes autodialer",
    "page.runCampaign.title": "Lancer la campagne",
    "page.runCampaign.subtitle": "Lancez une campagne + liste de contacts, puis suivez appels, logs et DTMF.",
    "page.campaignHistory.title": "Historique des campagnes",
    "page.campaignHistory.subtitle": "Historique complet avec répondu, échec, DTMF et détails audio/TTS.",
    "page.contacts.title": "Contacts",
    "page.contacts.subtitle": "Créez et gérez plusieurs listes de contacts.",
    "page.liveCalls.title": "Appels en direct",
    "page.liveCalls.subtitle": "Surveillance des appels en temps réel",
    "page.cdr.title": "Journaux d'appels (CDR)",
    "page.cdr.subtitle": "Enregistrements d'appels campagne depuis la base locale.",
    "page.callerId.title": "Comptes SIP",
    "page.callerId.subtitle": "Gérez utilisateurs SIP, trunks et caller IDs.",
    "page.settings.title": "Paramètres",
    "page.settings.subtitle": "Choisissez le compte SIP et caller ID par défaut pour les campagnes.",
    "page.profile.title": "Profil",
    "page.profile.subtitle": "Identité du compte, sécurité et résumé d'abonnement.",
    "page.subscription.title": "Abonnement",
    "page.subscription.subtitle": "Activez les plans autodialer avec le solde de votre compte CyberX.",
  },
  pt: {
    "header.active": "Ativo",
    "header.inactive": "Inativo",
    "header.adminAccount": "Conta Admin",
    "header.wallet": "Carteira",
    "header.dtmfNotifications": "Notificações DTMF",
    "header.noDtmfNotifications": "Ainda não há notificações DTMF.",
    "header.clear": "Limpar",
    "header.openProfile": "Abrir perfil",
    "header.openAdminSecurity": "Abrir segurança admin",
    "header.notSet": "Não definido",
    "header.now": "Agora",
    "header.dtmfFrom": "DTMF '{{dtmf}}' de {{number}}",
    "header.language": "Idioma",

    "menu.dashboard": "Painel",
    "menu.campaigns": "Campanhas",
    "menu.campaign": "Campanha",
    "menu.runCampaign": "Executar Campanha",
    "menu.campaignHistory": "Histórico de Campanhas",
    "menu.contacts": "Contatos",
    "menu.liveCalls": "Chamadas ao Vivo",
    "menu.callLogs": "Logs de Chamadas (CDR)",
    "menu.callerId": "Caller ID",
    "menu.subscription": "Assinatura",
    "menu.settings": "Configurações",
    "menu.logout": "Sair",

    "menu.adminDashboard": "Painel Admin",
    "menu.telegramUsers": "Usuários Telegram",
    "menu.adminLiveLogs": "Chamadas & Logs ao Vivo",
    "menu.userCampaigns": "Campanhas dos Usuários",
    "menu.allUsersCdrs": "CDRs de Todos os Usuários",
    "menu.activityLogs": "Logs de Atividade",
    "menu.broadcast": "Transmissão",
    "menu.adminSecurity": "Segurança Admin",

    "login.title": "Entrar na sua conta",
    "login.subtitle": "Faça login com as credenciais SIP da sua conta CyberX",
    "login.username": "Usuário",
    "login.password": "Senha",
    "login.rememberMe": "Lembrar de mim",
    "login.forgotPassword": "Esqueceu a senha?",
    "login.signIn": "Entrar",
    "login.signingIn": "Entrando...",
    "login.usernamePlaceholder": "Usuário",
    "login.passwordPlaceholder": "Senha",
    "login.hidePassword": "Ocultar senha",
    "login.showPassword": "Mostrar senha",

    "page.dashboard.title": "Painel",
    "page.dashboard.subtitle": "Bem-vindo de volta! Aqui está sua visão geral.",
    "page.campaigns.title": "Campanhas",
    "page.campaigns.subtitle": "Gerencie suas campanhas de autodialer",
    "page.runCampaign.title": "Executar Campanha",
    "page.runCampaign.subtitle": "Inicie por campanha + lista de contatos e acompanhe chamadas, logs e DTMF.",
    "page.campaignHistory.title": "Histórico de Campanhas",
    "page.campaignHistory.subtitle": "Histórico completo com atendidas, falhas, DTMF e detalhes de áudio/TTS.",
    "page.contacts.title": "Contatos",
    "page.contacts.subtitle": "Crie e gerencie várias listas de contatos.",
    "page.liveCalls.title": "Chamadas ao Vivo",
    "page.liveCalls.subtitle": "Monitoramento de chamadas em tempo real",
    "page.cdr.title": "Logs de Chamadas (CDR)",
    "page.cdr.subtitle": "Registros de campanha do banco local do discador.",
    "page.callerId.title": "Contas SIP",
    "page.callerId.subtitle": "Gerencie usuários SIP, contas trunk e caller IDs.",
    "page.settings.title": "Configurações",
    "page.settings.subtitle": "Escolha conta SIP e caller ID padrão para campanhas.",
    "page.profile.title": "Perfil",
    "page.profile.subtitle": "Identidade da conta, segurança e resumo da assinatura.",
    "page.subscription.title": "Assinatura",
    "page.subscription.subtitle": "Ative planos autodialer com o saldo da sua conta CyberX.",
  },
};

function isLanguageCode(value: string): value is LanguageCode {
  return LANGUAGE_META.some((item) => item.code === value);
}

function replaceParams(
  value: string,
  params?: Record<string, string | number>,
): string {
  if (!params) return value;
  return value.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, (_, key: string) => {
    if (!(key in params)) return "";
    return String(params[key]);
  });
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const cached = localStorage.getItem(STORAGE_KEY) || "";
    if (isLanguageCode(cached)) return cached;
    return "en";
  });

  const setLanguage = (next: LanguageCode) => {
    setLanguageState(next);
    localStorage.setItem(STORAGE_KEY, next);
  };

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      locale: LANGUAGE_LOCALES[language] || LANGUAGE_LOCALES.en,
      setLanguage,
      t: (key, params, fallback) => {
        const primary = DICTIONARY[language]?.[key];
        const fromEnglish = DICTIONARY.en[key];
        const resolved = primary || fromEnglish || fallback || key;
        return replaceParams(resolved, params);
      },
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
