const express = require('express');
const router  = express.Router();
const { v4: uuidv4 } = require('uuid');
const { exec } = require('child_process');
const fs  = require('fs');
const db  = require('../db');
const ami = require('../ami');
const { rebuildQueue, queueName } = require('./queue');
const { requireAccount } = require('../account');

router.use(requireAccount);

const CONTAINER = process.env.ASTERISK_CONTAINER || 'local-asterisk';

// ─── Rebuild sip_agents.conf in Asterisk container & reload SIP ───────────────
async function reloadAsteriskAgents() {
  const agents = await db.all('SELECT * FROM agents ORDER BY created_at');

  let conf = '; Auto-generated by AutoDialer — do not edit manually\n\n';
  for (const a of agents) {
    conf += `[${a.username}]\n`;
    conf += `type=friend\n`;
    conf += `host=dynamic\n`;
    conf += `secret=${a.password}\n`;
    conf += `context=autodialer\n`;
    if (a.caller_id) conf += `callerid=${a.caller_id}\n`;
    conf += `nat=yes\nqualify=yes\ninsecure=invite,port\n\n`;
  }

  const tmp = '/tmp/sip_agents.conf';
  fs.writeFileSync(tmp, conf);

  await new Promise((resolve, reject) => {
    exec(`docker cp ${tmp} ${CONTAINER}:/etc/asterisk/sip_agents.conf`, (err) =>
      err ? reject(new Error('docker cp failed: ' + err.message)) : resolve()
    );
  });

  // Add #include if not already in sip.conf
  await new Promise((resolve) => {
    exec(
      `docker exec ${CONTAINER} sh -c "grep -q 'sip_agents.conf' /etc/asterisk/sip.conf || echo '#include sip_agents.conf' >> /etc/asterisk/sip.conf"`,
      resolve
    );
  });

  // Reload SIP
  await new Promise((resolve) => {
    exec(`docker exec ${CONTAINER} asterisk -rx "sip reload"`, (err, stdout) => {
      if (err) console.warn('[Agents] sip reload warning:', err.message);
      else console.log('[Agents] SIP reloaded:', stdout.trim());
      resolve();
    });
  });
}

// ─── Check peer registration status via AMI ───────────────────────────────────
async function peerStatus(username) {
  try {
    const res = await ami.action({ action: 'SIPshowpeer', peer: username });
    const st  = (res.status || res.Status || '').toLowerCase();
    if (st.includes('ok') || st.includes('registered')) return 'online';
    if (st.includes('unregistered') || st.includes('unreachable')) return 'offline';
    return 'unknown';
  } catch {
    return 'unknown';
  }
}

// ─── Routes ───────────────────────────────────────────────────────────────────

// GET all agents for this account (with live AMI status)
router.get('/', async (req, res) => {
  try {
    const acct   = req.accountId;
    const agents = await db.all('SELECT * FROM agents WHERE account_id = ? ORDER BY created_at', [acct]);
    const result = await Promise.all(
      agents.map(async (a) => ({ ...a, status: await peerStatus(a.username) }))
    );
    res.json(result);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// POST create agent
router.post('/', async (req, res) => {
  try {
    const acct = req.accountId;
    const { name, password, caller_id } = req.body || {};
    if (!name || !password)
      return res.status(400).json({ error: 'name and password are required' });

    // Auto-generate username: {accountPrefix}a1, {accountPrefix}a2, …
    // Use first 8 chars of account id as prefix to ensure global uniqueness
    const prefix = acct.replace(/[^a-z0-9]/gi, '').toLowerCase().substring(0, 8) || 'agent';
    const pattern = `${prefix}a%`;
    const existing = await db.all('SELECT username FROM agents WHERE username LIKE ?', [pattern]);
    const regex = new RegExp(`^${prefix}a(\\d+)$`);
    const usedNums = existing
      .map(a => parseInt((a.username.match(regex) || [])[1]))
      .filter(n => !isNaN(n));
    let nextNum = 1;
    while (usedNums.includes(nextNum)) nextNum++;
    const clean = `${prefix}a${nextNum}`;

    const id = uuidv4();
    await db.run(
      'INSERT INTO agents (id, name, username, password, caller_id, account_id) VALUES (?, ?, ?, ?, ?, ?)',
      [id, name, clean, password, caller_id || '', acct]
    );

    await reloadAsteriskAgents();
    await rebuildQueue(acct).catch(() => {});

    const agent = await db.get('SELECT * FROM agents WHERE id = ?', [id]);
    res.json({ ...agent, status: 'unknown' });
  } catch (err) {
    if (err.message.includes('unique') || err.message.includes('duplicate'))
      return res.status(400).json({ error: 'Username already exists' });
    res.status(500).json({ error: err.message });
  }
});

// PUT update agent (name / password / caller_id — not username)
router.put('/:id', async (req, res) => {
  try {
    const acct     = req.accountId;
    const existing = await db.get('SELECT * FROM agents WHERE id = ? AND account_id = ?', [req.params.id, acct]);
    if (!existing) return res.status(404).json({ error: 'Not found' });

    const { name, password, caller_id } = req.body || {};
    await db.run(
      'UPDATE agents SET name = COALESCE(?, name), password = COALESCE(?, password), caller_id = COALESCE(?, caller_id) WHERE id = ?',
      [name, password, caller_id !== undefined ? caller_id : null, req.params.id]
    );

    await reloadAsteriskAgents();
    await rebuildQueue(acct).catch(() => {});

    const agent = await db.get('SELECT * FROM agents WHERE id = ?', [req.params.id]);
    res.json({ ...agent, status: await peerStatus(agent.username) });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// DELETE agent
router.delete('/:id', async (req, res) => {
  try {
    const acct     = req.accountId;
    const existing = await db.get('SELECT * FROM agents WHERE id = ? AND account_id = ?', [req.params.id, acct]);
    if (!existing) return res.status(404).json({ error: 'Not found' });

    await db.run('DELETE FROM agents WHERE id = ? AND account_id = ?', [req.params.id, acct]);
    await reloadAsteriskAgents();
    await rebuildQueue(acct).catch(() => {});
    res.json({ success: true });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

module.exports = router;
