const express = require('express');
const router  = express.Router();
const { exec } = require('child_process');
const fs   = require('fs');
const path = require('path');
const db   = require('../db');
const ami  = require('../ami');
const { requireAccount } = require('../account');

const CONTAINER = process.env.ASTERISK_CONTAINER || 'local-asterisk';

function execP(cmd) {
  return new Promise((res, rej) =>
    exec(cmd, (err, out) => err ? rej(err) : res(out || ''))
  );
}

/** Derive safe queue name from Magnus account ID */
function queueName(accountId) {
  const safe = (accountId || 'default').replace(/[^a-z0-9]/gi, '').toLowerCase().substring(0, 12);
  return `aq-${safe}`;
}

// ─── Rebuild ALL queues (one per account) + all SIP agent peers ───────────────
async function rebuildQueue(accountId) {
  // Rebuild sip_agents.conf for ALL agents across all accounts (unique usernames)
  const allAgents = await db.all('SELECT * FROM agents ORDER BY account_id, created_at');
  let sipConf = '; Auto-generated by AutoDialer — do not edit manually\n\n';
  for (const a of allAgents) {
    sipConf += `[${a.username}]\ntype=friend\nhost=dynamic\nsecret=${a.password}\ncontext=autodialer\n`;
    if (a.caller_id) sipConf += `callerid=${a.caller_id}\n`;
    sipConf += 'nat=force_rport,comedia\ncanreinvite=no\nqualify=yes\ninsecure=invite,port\n\n';
  }
  fs.writeFileSync('/tmp/sip_agents.conf', sipConf);
  await execP(`docker cp /tmp/sip_agents.conf ${CONTAINER}:/etc/asterisk/sip_agents.conf`);
  await execP(
    `docker exec ${CONTAINER} sh -c "grep -q 'sip_agents.conf' /etc/asterisk/sip.conf || echo '#include sip_agents.conf' >> /etc/asterisk/sip.conf"`
  );

  // Rebuild queues_autodialer.conf — one [queue] section per account
  const accounts = await db.all('SELECT DISTINCT account_id FROM agents');
  let qConf = '; Auto-generated by AutoDialer — do not edit manually\n\n';
  for (const row of accounts) {
    const acct = row.account_id;
    const cfg  = await db.get('SELECT * FROM queue_config WHERE account_id = ?', [acct]);
    const members = await db.all(
      'SELECT username FROM agents WHERE account_id = ? AND in_queue = true ORDER BY created_at', [acct]
    );
    const qn = queueName(acct);
    qConf += `[${qn}]\n`;
    qConf += `strategy=${(cfg && cfg.strategy) || 'ringall'}\n`;
    qConf += `timeout=${(cfg && cfg.agent_timeout) || 15}\n`;
    qConf += `retry=5\nmaxlen=0\n`;
    qConf += `musicclass=${qn}-moh\n`;
    qConf += `wrapuptime=5\njoinempty=yes\nleavewhenempty=no\n`;
    for (const m of members) qConf += `member => SIP/${m.username},0,${m.username}\n`;
    qConf += '\n';
  }
  fs.writeFileSync('/tmp/queues_autodialer.conf', qConf);
  await execP(`docker cp /tmp/queues_autodialer.conf ${CONTAINER}:/etc/asterisk/queues_autodialer.conf`);
  await execP(
    `docker exec ${CONTAINER} sh -c "grep -q 'queues_autodialer.conf' /etc/asterisk/queues.conf 2>/dev/null || echo '#include queues_autodialer.conf' >> /etc/asterisk/queues.conf"`
  );

  // MOH config — one class per account
  let mohConf = '; Auto-generated by AutoDialer — do not edit manually\n\n';
  for (const row of accounts) {
    const acct = row.account_id;
    const qn   = queueName(acct);
    const cfg  = await db.get('SELECT * FROM queue_config WHERE account_id = ?', [acct]);
    mohConf += `[${qn}-moh]\nmode=files\ndirectory=${qn}-moh\nrandom=yes\n\n`;
    // Copy MOH audio file if set
    if (cfg && cfg.moh_file) {
      const localFile = path.join(__dirname, '../../data/audio', cfg.moh_file);
      if (fs.existsSync(localFile)) {
        await execP(`docker exec ${CONTAINER} sh -c "mkdir -p /var/lib/asterisk/moh/${qn}-moh 2>/dev/null || mkdir -p /usr/share/asterisk/moh/${qn}-moh 2>/dev/null || true"`);
        await execP(`docker cp "${localFile}" ${CONTAINER}:/var/lib/asterisk/moh/${qn}-moh/hold${path.extname(cfg.moh_file)}`).catch(() => {});
      }
    }
  }
  fs.writeFileSync('/tmp/moh_autodialer.conf', mohConf);
  await execP(`docker cp /tmp/moh_autodialer.conf ${CONTAINER}:/etc/asterisk/musiconhold_autodialer.conf`);
  await execP(
    `docker exec ${CONTAINER} sh -c "grep -q 'musiconhold_autodialer.conf' /etc/asterisk/musiconhold.conf 2>/dev/null || echo '#include musiconhold_autodialer.conf' >> /etc/asterisk/musiconhold.conf"`
  );

  // Reload everything
  await execP(`docker exec ${CONTAINER} asterisk -rx "sip reload"`).catch(() => {});
  await execP(`docker exec ${CONTAINER} asterisk -rx "module reload app_queue.so"`).catch(() => {});
  await execP(`docker exec ${CONTAINER} asterisk -rx "module reload res_musiconhold.so"`).catch(() => {});
  console.log(`[Queue] Rebuilt for account=${accountId || 'all'}`);
}

// ─── AMI QueueStatus collector ────────────────────────────────────────────────
function getQueueStatus(qName) {
  return new Promise((resolve) => {
    const members = [];
    const entries = [];

    const onMember = (e) => { if ((e.queue || '').toLowerCase() === qName.toLowerCase()) members.push(e); };
    const onEntry  = (e) => { if ((e.queue || '').toLowerCase() === qName.toLowerCase()) entries.push(e); };
    const onDone   = () => { cleanup(); resolve({ members, entries }); };

    function cleanup() {
      ami.off('queuemember', onMember);
      ami.off('queueentry', onEntry);
      ami.off('queuestatuscomplete', onDone);
    }

    ami.on('queuemember', onMember);
    ami.on('queueentry', onEntry);
    ami.on('queuestatuscomplete', onDone);

    ami.action({ action: 'QueueStatus', queue: qName }).catch(() => {});
    setTimeout(() => { cleanup(); resolve({ members, entries }); }, 3000);
  });
}

const MEMBER_STATUS = {
  '0': 'unknown', '1': 'free', '2': 'in-call', '3': 'busy',
  '4': 'invalid', '5': 'offline', '6': 'ringing', '7': 'ringing',
};

// ─── Routes ───────────────────────────────────────────────────────────────────

router.use(requireAccount);

// GET /api/queue — config + agent membership for this account
router.get('/', async (req, res) => {
  try {
    const acct = req.accountId;
    let cfg = await db.get('SELECT * FROM queue_config WHERE account_id = ?', [acct]);
    if (!cfg) cfg = { account_id: acct, strategy: 'ringall', agent_timeout: 15, max_wait: 120, moh_file: '' };
    const agents = await db.all(
      'SELECT id, name, username, in_queue FROM agents WHERE account_id = ? ORDER BY created_at', [acct]
    );
    res.json({ config: cfg, agents, queue_name: queueName(acct) });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// PUT /api/queue — update config for this account
router.put('/', async (req, res) => {
  try {
    const acct = req.accountId;
    const { strategy, agent_timeout, max_wait, moh_file } = req.body || {};
    await db.run(`
      INSERT INTO queue_config (account_id, strategy, agent_timeout, max_wait, moh_file)
      VALUES (?, ?, ?, ?, ?)
      ON CONFLICT (account_id) DO UPDATE SET
        strategy = EXCLUDED.strategy, agent_timeout = EXCLUDED.agent_timeout,
        max_wait = EXCLUDED.max_wait, moh_file = EXCLUDED.moh_file
    `, [acct, strategy || 'ringall', parseInt(agent_timeout)||15, parseInt(max_wait)||120, moh_file||'']);
    await rebuildQueue(acct);
    const cfg = await db.get('SELECT * FROM queue_config WHERE account_id = ?', [acct]);
    res.json({ ...cfg, queue_name: queueName(acct) });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// PUT /api/queue/member/:agentId — toggle in_queue
router.put('/member/:agentId', async (req, res) => {
  try {
    const acct = req.accountId;
    const inQueue = req.body.in_queue !== false;
    await db.run('UPDATE agents SET in_queue = ? WHERE id = ? AND account_id = ?',
      [inQueue, req.params.agentId, acct]);
    await rebuildQueue(acct);
    res.json({ success: true });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// GET /api/queue/monitor — live queue + agent status via AMI
router.get('/monitor', async (req, res) => {
  try {
    const acct = req.accountId;
    const qn   = queueName(acct);
    const { members, entries } = await getQueueStatus(qn);

    const agentRows = await db.all(
      'SELECT name, username FROM agents WHERE account_id = ? ORDER BY created_at', [acct]
    );
    const nameMap = {};
    agentRows.forEach(a => { nameMap[`SIP/${a.username}`] = a.name; });

    const agentStatus = members.map(m => ({
      name:      nameMap[m.location] || m.membername || m.location,
      username:  m.membername || '',
      location:  m.location || '',
      status:    MEMBER_STATUS[m.status] || 'unknown',
      statusNum: m.status,
      callsTaken: parseInt(m.callstaken) || 0,
      lastCall:  m.lastcall ? new Date(parseInt(m.lastcall) * 1000).toLocaleTimeString() : '—',
      paused:    m.paused === '1',
    }));

    const callers = entries.map(e => ({
      position:  parseInt(e.position) || 0,
      callerid:  e.calleridnum || e.callerid || '—',
      channel:   e.channel || '',
      wait:      parseInt(e.wait) || 0,
    }));

    res.json({ queue: qn, agents: agentStatus, callers });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

module.exports = { router, rebuildQueue, queueName };
