const express = require('express');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');
const db = require('../db');
const { sendCommand } = require('../ami');

const sleep = (ms) => new Promise(r => setTimeout(r, ms));

const router = express.Router();

// GET all SIP accounts
router.get('/', (req, res) => {
  const accounts = db.prepare('SELECT * FROM sip_accounts ORDER BY created_at DESC').all();
  res.json(accounts);
});

// POST create/update SIP account
router.post('/', async (req, res) => {
  const { name, username, password, domain, port, caller_id } = req.body;
  if (!username || !password || !domain) {
    return res.status(400).json({ error: 'username, password, domain required' });
  }

  const id = uuidv4();
  db.prepare(`
    INSERT INTO sip_accounts (id, name, username, password, domain, port, caller_id)
    VALUES (?, ?, ?, ?, ?, ?, ?)
  `).run(id, name || username, username, password, domain, port || 5060, caller_id || '');

  writeSipConfig();
  // Reload SIP — must wait for it to fully apply before responding
  await sendCommand('sip reload');
  await sleep(2000); // allow chan_sip to re-process peer registrations
  await sendCommand('module reload chan_sip.so'); // force full in-memory refresh
  await sleep(2000);
  console.log('[SIP] Config written and module reloaded');

  res.json({ id, message: 'SIP account saved and Asterisk fully reloaded. Wait ~5s then check Status.' });
});

// PUT update SIP account
router.put('/:id', async (req, res) => {
  const { name, username, password, domain, port, caller_id } = req.body;
  db.prepare(`
    UPDATE sip_accounts SET name=?, username=?, password=?, domain=?, port=?, caller_id=?
    WHERE id=?
  `).run(name, username, password, domain, port || 5060, caller_id || '', req.params.id);

  writeSipConfig();
  await sendCommand('sip reload');
  await sleep(2000);
  await sendCommand('module reload chan_sip.so');
  res.json({ message: 'Updated and Asterisk reloaded.' });
});

// DELETE SIP account
router.delete('/:id', async (req, res) => {
  db.prepare('DELETE FROM sip_accounts WHERE id = ?').run(req.params.id);
  writeSipConfig();
  await sendCommand('sip reload');
  await sleep(2000);
  await sendCommand('module reload chan_sip.so');
  res.json({ message: 'Deleted and Asterisk reloaded.' });
});

// GET SIP registration status
router.get('/:id/status', async (req, res) => {
  const { res: amiRes } = await sendCommand('sip show registry');
  const output = Array.isArray(amiRes?.output) ? amiRes.output.join('\n') : (amiRes?.output || '');
  res.json({ output, registered: output.includes('Registered') });
});

function writeSipConfig() {
  const sipConfPath = process.env.ASTERISK_SIP_CONF;
  if (!sipConfPath) return;

  const accounts = db.prepare('SELECT * FROM sip_accounts').all();
  let content = '; Auto-generated by CyberX AutoDialer — DO NOT EDIT MANUALLY\n';
  content += '; Register lines (must be before any [section] to stay in [general] context)\n';

  for (const acc of accounts) {
    content += `register => ${acc.username}:${acc.password}@${acc.domain}/${acc.username}\n`;
  }

  content += '\n; Peer configs\n';
  for (const acc of accounts) {
    content += `
[${acc.username}]
type=peer
secret=${acc.password}
username=${acc.username}
host=${acc.domain}
fromdomain=${acc.domain}
fromuser=${acc.username}
defaultuser=${acc.username}
context=from-trunk
disallow=all
allow=ulaw
allow=alaw
allow=gsm
insecure=port,invite
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
directmedia=no
`;
  }

  fs.writeFileSync(sipConfPath, content, 'utf8');
  console.log('[SIP] Config written to', sipConfPath);
}

module.exports = router;
